### ISSUE TITLE
Getting this error after cloning from this repo

### ISSUE THREAD

**Issue by n1k0l4y** [antlancer-solutions/Simple-Face-Recognition-App-CS#1]
'Simple Face Recognition App.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Simple Face Recognition App.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\nikol\Source\Repos\Simple-Face-Recognition-App-CS4\Simple Face Recognition App\bin\Debug\Simple Face Recognition App.exe'. Symbols loaded.
'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\Users\nikol\Source\Repos\Simple-Face-Recognition-App-CS4\Simple Face Recognition App\bin\Debug\Emgu.CV.World.dll'. Module was built without symbols.
'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileNotFoundException' in Emgu.CV.World.dll
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Emgu.CV.World.dll
File '{0}' not found

'Simple Face Recognition App.exe' (CLR v4.0.30319: Simple Face Recognition App.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Unhandled Exception: System.IO.FileNotFoundException: File '{0}' not found
   at Emgu.CV.CascadeClassifier..ctor(String fileName)
   at Simple_Face_Recognition_App.Form1..ctor() in C:\Users\nikol\Source\Repos\Simple-Face-Recognition-App-CS4\Simple Face Recognition App\Form1.cs:line 28
   at Simple_Face_Recognition_App.Program.Main() in C:\Users\nikol\Source\Repos\Simple-Face-Recognition-App-CS4\Simple Face Recognition App\Program.cs:line 19
The program '[18708] Simple Face Recognition App.exe' has exited with code 0 (0x0).

**Comment by akakJnr** [comment]
You have missing dependencies
